### ISSUE TITLE
[Feature] Option to set width of images

### ISSUE THREAD

**Issue by domiSchenk** [kufii/CodeSnap#25]
It would be nice to have a option to fix the width.

This would greatly enhance readability and design for documentations.

**Comment by havremunken** [comment]
Second that! Or even an option to make it go as wide as necessary to make sure no lines are wrapped in the screenshot.

I realize this is probably not a requirement a lot of people have, so justification: I am making a video to teach some concepts on source code. Part of the video will zoom into the source code screenshots quite a bit. Therefore I have to make large screenshots with a huge font size, so that it looks good no matter how close the "virtual" camera gets to the text. If I set text size 50 (just an example) and try to do a CodeSnap screenshot, even if I go down to the right corner and expand it until it is big enough, there are usually some formatting issues.

**Comment by MatrosSkin** [comment]
@kufii why this issue closed?

**Comment by OnkelTem** [comment]
### Width

I wonder why setting _precise_ `width` was not among the options from the beginning.
Currently when you scale your image using CodeSnap, you don't see the `width` value. 

Twitter wants an image of a `504px` width while displaying in a feed, or `600px`, while on a separate page. Many blogs also want some minimum width of inserted images. Otherwise images are gonna be either scaled up or down.

Here is another tool which perfectly does the job: https://carbon.now.sh/ 

### Height

Height is another issue. If your image is vertical, Twitter will downscale it for the tweets list output. So you actually need to set either `ratio` or `height` along with `width`.

Seeing this closed doesn't make it promising really. So I feel like I'll be fine with Carbon for now.

**Comment by tanthuann** [comment]
You can change the width of image follow this way.

Access this:

```$HOME\.vscode-server\extensions\adpyke.codesnap-1.3.4\webview\style.css```
or
```$HOME\.vscode\extensions\adpyke.codesnap-1.3.4\webview\style.css```

Change the width to your expectation:

![image](https://github.com/kufii/CodeSnap/assets/44896550/fc1f11c4-7f39-44f6-a22a-e730f1b31918)

Note: if you save this file, you should reopen webview

![image](https://github.com/kufii/CodeSnap/assets/44896550/89e23845-ce18-4b94-acfe-ec8ca712d628)

**Comment by passee** [comment]
Guys I had the same "problem".
But I think we are all blind.

**There is literally "resize: horizontal" implemented and you can just drag it to the desired width.**
